name: Run E2E Tests (Linux)
on: workflow_call
jobs:
    e2e-linux:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
          # Checkout the PR branch
          - name: Checkout Code
            uses: actions/checkout@v4
            with:
              ref: ${{ github.event.pull_request.head.ref }}
              repository: ${{ github.event.pull_request.head.repo.full_name }}

          # Set up Docker Buildx
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
            
          # Login to GitHub Container Registry
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
            
          # Build Docker image with caching
          - name: Build E2E tests Docker Image
            uses: docker/build-push-action@v5
            with:
              context: .
              push: false
              load: true
              tags: mynah-ui-e2e:latest
              cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/mynah-ui-e2e:buildcache
              cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/mynah-ui-e2e:buildcache,mode=max

          # Run the Docker container
          - name: Run E2E tests Docker Container
            run: npm run docker:run
            env:
              WEBKIT_FORCE_COMPLEX_TEXT: 0
    
          # Extract test results from Docker container
          - name: Extract test results from Docker container
            if: always()
            run: npm run docker:extract
              
          # Upload test results as artifact
          - name: Upload test results
            uses: actions/upload-artifact@v4
            if: always()
            with:
              name: test-results
              path: ./ui-tests/__results__
              retention-days: 30
    report:
      needs: e2e-linux
      if: always()
      uses: ./.github/workflows/test_report.yml
