name: Run Unit tests
on: workflow_call
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@aws'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Unit tests
        run: npm run tests:unit

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coverage